### PR TITLE
Snake Game Implementation

### PR DESCRIPTION
**Pull request by ShaneCreedon**
Built a very simple Snake game with randomly spawning food and collision detection on the walls and snake. To run just launch it with python2. It requires the Pygame library.

### CODE REVIEW

**Comment by Prouser123** [comment]
Thanks for contributing and taking the time to fix issues, (🥇) very much appreciated. Just a few housekeeping items left (like adding it to the list of programs in the code and documentation) and then we are ready for a merge into master. I'm happy to do that myself but you are happy to do so if you wish.

**Comment by ShaneCreedon** [comment]
Yeah, I'll fix those things and finish the checklist ^^

**Comment by ShaneCreedon** [comment]
Checklist Complete.

**Comment by Prouser123** [comment]
Thanks. I'm a little busy right now, but should hopefully be able to merge soon.

**Comment by ShaneCreedon** [comment]
Awesome ^^

**Comment by Prouser123** [comment]
@ShaneCreedon 

I've been reviewing your code for the last half hour, and your program works fine when running directly. 👏 
I made a few changes (adding pygame to the pip requirements and renaming the file to `snake.py` as PyOS filters out commands with underscores, like `__init__`, from being run in the script), but there is one issue remaining.

You are using a lot of `__init__` calls to set up pygame, but that has the side effect of running pygame when PyOS is first run. You can see this if you comment out the line in `main.py` that clears the screen when first running the script, before the main loop. (`line 39 : internal.extra.cls`)

**Currently all PyOS programs run only the `app()` function, with no `__init__` calls.** This is so that no part of the code would run before the user enters the relevant command. Is it possible that we could remove these `__init__` calls and run everything from the `app()` function?

I have been messing around with that for a while, but that main issue is that a lot of `self` components are created in `Snake.__init__` and `Launcher.__init__`. This means that these do not exist or are not in the right locations when running `__init__` from `app()` (example: renaming `__init__(self)` to `init()`, running from `app()` and creating a reference from `self` to `Snake()` causes some elements to not exist, like `self.direction`. 

Sorry to do this to you, especially after all your work on code quality, but I'm a little stuck here. Is it possible that you could update your script to not use `__init__` calls so that everything is run through `app()`? As mentioned earlier, you could try renaming `__init__` to `init()`, and go from there.

Regardless, many thanks for all your contributions thus far.
~ @Prouser123

**Comment by ShaneCreedon** [comment]
Yeah @Prouser123 I'll give it a look

**Comment by Prouser123** [comment]
Wrapped in a try statement to escape the crash that would occur if you do not use `sys.exit()`, so that when running from within PyOS, PyOS stays running after the end of the game.

**Comment by Prouser123** [comment]
@ShaneCreedon Let me take care of `codacy-bot`.

**Pull request merged**
